title: Kangwei Shi's Homepage
page-top-title: Kangwei Shi
# top-section-bg-text: Management Information Systems
home-subtitle: Kangwei Shi
copyright-text: '&copy; Kangwei Shi 2025. All Rights Reserved.'
