title: Sen Li's Homepage
page-top-title: Sen Li
top-section-bg-text: Management Information Systems
home-subtitle: Sen Li&ensp;|&ensp;史康威
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
