title: Kangwei Shi's Homepage
page-top-title: Kangwei Shi
top-section-bg-text: Management Information Systems
home-subtitle: Kangwei Shi&ensp;|&ensp;史康威
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
